<div id="idhm" style="width: 900px;">
    <div class="areatitle">O IVS</div>
    <div id="texto_idhm">
        <p>A criação do IVS se deu no âmbito da Rede Ipea, no escopo do projeto Mapeamento da Vulne¬rabilidade Social nas Regiões Metropolitanas do Brasil, proposto, inicialmente, pela Fundação Sistema Estadual de Análise de Dados (Seade), em atendimento à chamada pública Ipea/ Proedes no 01/2011, reunindo diversas instituições sob a coordenação nacional do Ipea, tais como: a Fundação Seade (instituição proponente) e instituições estaduais de pesquisa das cinco macrorregiões brasileiras, a saber: Instituto Paranaense de Desenvolvimento Econômico e Social – Ipardes (PR), na região Sul; Fundação Centro Estadual de Estatísticas, Pesquisas e Formação de Servidores do Rio de Janeiro – Ceperj (RJ), na região Sudeste; a Superintendência de Estudos Econômicos e Sociais da Bahia – SEI (BA), na região Nordeste; a Fundação Amazônia de Amparo a Estudos e Pesquisas do Pará – Fapespa (PA), na região Norte; e a Secretaria de Desenvolvimento da Região Metropolitana de Goiânia – Segplan (GO), na região Centro-Oeste; além da Fundação João Pinheiro – FJP (MG), parceira do Ipea no ADH. </p>
        <p>Nessa discussão, comum aos debates em torno da construção de indicadores e índices socioeconômicos, a primeira questão (e ponto de partida decisivo e condicionador das demais decisões metodológicas do projeto) diz respeito a quais fontes e bases de dados utilizar: dados de registros administrativos ou dados secundários das pesquisas realizadas pelo Instituto Brasileiro de Geografia e Estatística (IBGE), notadamente os censos demográficos e a Pesquisa Nacional por Amostra de Domicílios (PNAD) dos períodos analisados. </p>
        <p>Registros administrativos oferecem dados mais recentes, de escopo e amplitude mais amplos do que aqueles encontrados nas pesquisas do IBGE. Por outro lado, os dados do IBGE, apesar de mais limitados em termos temporais, de escopo e amplitude do campo informacio¬nal, oferecem a vantagem de procederem fonte única e de serem coletados por metodologia uniforme, aplicada com a mesma validade estatística e rigor em todo o território nacional, em diferentes escalas territoriais. </p>
        <p>Assim, embora fosse interessante poder contar com dados mais recentes, optou-se pelos dados do IBGE como base para a construção do IVS. Ademais, decidiu-se pela utiliza¬ção apenas dos dados colhidos pelos censos demográficos, já que as PNADs não permitem o recorte municipal, o que inviabilizaria o propósito inicial de se obter indicadores para esta escala territorial. </p>
        <p>Em larga medida, esta decisão seminal condicionou outras decisões tomadas ao longo do projeto. A utilização da base de dados dos censos demográficos exigiu que fosse feita uma leitura criteriosa dos dois questionários utilizados pelo IBGE (questionário do universo e questionário da amostra), no <i>Censo demográfico 2010</i>, visando extrair deles as informações que apontassem situações de exclusão e de vulnerabilidade.</p>
        <p>Este trabalho, iniciado na primeira oficina do projeto (em novembro de 2012), gerou diversas propostas de cestas de indicadores e culminou no estabelecimento de um diálogo entre o IVS e a plataforma do ADH no Brasil, um projeto desenvolvido por meio da parceria Ipea; o Programa das Nações Unidas para o Desenvolvimento (PNUD); e a FJP, que tem na publicação do IDHM seu carro-chefe. </p>
        <p>A partir das propostas trazidas pelas equipes, por meio da leitura e análise dos ques-tionários do <i>Censo demográfico 2010</i>, identificou-se que os indicadores constantes no ADH respondiam aos anseios da equipe em termos do conjunto de aspectos que permitem retratar diferentes situações indicativas de vulnerabilidade social. </p>
        <p>Ajustes nos algoritmos dos indicadores de vulnerabilidade social do ADH foram sugeridos pela equipe envolvida em sua construção, ao passo que os indicadores do ADH foram assumidos como a base de dados para estruturação da proposta do IVS, limitando-se o índice (e seus indica¬dores) ao leque de elementos e variáveis presentes no censo demográfico e, por extensão, no ADH. </p>
        <p>À medida que as bases de dados foram sendo construídas, com correções e ajustes de indicadores de pesos, de estruturação dos dados em diferentes dimensões, a proposta do IVS foi sendo amadurecida, com a sua submissão e avaliação por parte das equipes técnicas das instituições parceiras. </p>
        <p>Contando com representantes de instituições das cinco macrorregiões do país, a equipe do projeto lidou, ao longo desses dois anos de implementação do projeto, com diferentes desafios conceituais e metodológico-operacionais.</p>

    </div>
                <div class="clear"></div>

<?php
    $title2 = $lang_mng->getString("atlas_titleidhm");
    $meta_title2 = $lang_mng->getString("atlas_metaTitleidhm");
    $meta_description2 = $lang_mng->getString("atlas_metaDescricaoidhm");
?>  